[package]
name = "core_affinity"
version = "0.2.0"
authors = ["Philip Woods <elzairthesorcerer@gmail.com>"]

[dependencies]

[target.'cfg(target_os = "linux")'.dependencies]
libc = "^0.2.30"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = "^0.2.8"

[dev-dependencies]
num_cpus = "1.6.2"